parameters:
#    flux_design_pattern_playground.example.class: Flux\DesignPatternPlaygroundBundle\Example

services:
#    flux_design_pattern_playground.example:
#        class: %flux_design_pattern_playground.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
